env: "local"
db: 
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "12345"
  dbname: "postgres"
  sslmode: "disable"
http_server:
  address: "localhost:8081"
  timeout: 4s
  idle_timeout: 60s
token_ttl: 1h
